### ISSUE TITLE
Trouble running ftgrid

### ISSUE THREAD

**Issue by mjlagattuta** [source-foundry/manual-ttfa#5]
While following the install instructions and trying to run ftgrid on a `ttf` like this:
`$ ./ftgrid -w 1280 -h 600 -f 139 14 RobotoSlab-VF-sss.ttf`

 I ran into the following error:
```
could not allocate display surface
error = 0x0000, no error
```

For reference I am running Mac OSX Mojave 10.14 and have XQuartz installed. I have attempted to remedy this by restarting my machine, launching XQuartz, and even running the above command on xterm in XQuartz.

My folders are set up as follows:
```
.
├── freetype2
└── freetype2-demos
```

I am unsure what would cause this or what the error message means, any insight would be much appreciated :)

**Comment by chrissimpkins** [comment]
Thanks for submitting the report Mike.  

Can you also confirm whether you are attempting to compile the upstream freetype2-demo tools from the FreeType repository or the source from the [SF downstream derivative](https://github.com/source-foundry/freetype2-demos) that I mentioned on the README?  I can verify that the downstream project is behind changes in the upstream source.

**Comment by mjlagattuta** [comment]
Ah, I've got it working now! My mistake was installing X11 after compiling the freetype2-demos files.

I went through the install process again after having X11 installed. I did not realize that X11 had to be installed prior to compiling the freetype2-demos files so that the files can properly reference the path.

In the documentation I see that X11 is mentioned before the install instructions for the freetype2-demos, but perhaps it may be useful to note or emphasize that X11 should be installed first.

**Comment by chrissimpkins** [comment]
Ah, excellent!  

> I did not realize that X11 had to be installed prior to compiling the freetype2-demos files so that the files can properly reference the path.

How about we include a statement that indicates this in the **Important** block of text in this section: 

https://github.com/source-foundry/manual-ttfa#compile-ftgrid-executable

and pull that entire text section up to immediately beneath the `ftgrid` header?

**Comment by mjlagattuta** [comment]
Sounds good to me, that would definitely help.

**Comment by chrissimpkins** [comment]
Done!  Thanks Mike! Glad to hear that it is working.
